Drop table users;
CREATE TABLE users (
	ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    EMAIL           varchar(80),
	PASSWORD 		 varchar(80),
    CREATION_DATE            integer
);
Insert into users (email,password,creation_date) values ('test@test.com', 'test', 4234235)